// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb-auth-gen/authen.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b59a56bd496d6, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b59a56bd496d6, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Permission           string   `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b59a56bd496d6, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

type RegisterResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b59a56bd496d6, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CheckPermissionRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPermissionRequest) Reset()         { *m = CheckPermissionRequest{} }
func (m *CheckPermissionRequest) String() string { return proto.CompactTextString(m) }
func (*CheckPermissionRequest) ProtoMessage()    {}
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b59a56bd496d6, []int{4}
}

func (m *CheckPermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPermissionRequest.Unmarshal(m, b)
}
func (m *CheckPermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPermissionRequest.Marshal(b, m, deterministic)
}
func (m *CheckPermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPermissionRequest.Merge(m, src)
}
func (m *CheckPermissionRequest) XXX_Size() int {
	return xxx_messageInfo_CheckPermissionRequest.Size(m)
}
func (m *CheckPermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPermissionRequest proto.InternalMessageInfo

func (m *CheckPermissionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CheckPermissionResponse struct {
	Permission           string   `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPermissionResponse) Reset()         { *m = CheckPermissionResponse{} }
func (m *CheckPermissionResponse) String() string { return proto.CompactTextString(m) }
func (*CheckPermissionResponse) ProtoMessage()    {}
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d3b59a56bd496d6, []int{5}
}

func (m *CheckPermissionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPermissionResponse.Unmarshal(m, b)
}
func (m *CheckPermissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPermissionResponse.Marshal(b, m, deterministic)
}
func (m *CheckPermissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPermissionResponse.Merge(m, src)
}
func (m *CheckPermissionResponse) XXX_Size() int {
	return xxx_messageInfo_CheckPermissionResponse.Size(m)
}
func (m *CheckPermissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPermissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPermissionResponse proto.InternalMessageInfo

func (m *CheckPermissionResponse) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

func (m *CheckPermissionResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CheckPermissionResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "pb.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "pb.LoginResponse")
	proto.RegisterType((*RegisterRequest)(nil), "pb.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "pb.RegisterResponse")
	proto.RegisterType((*CheckPermissionRequest)(nil), "pb.CheckPermissionRequest")
	proto.RegisterType((*CheckPermissionResponse)(nil), "pb.CheckPermissionResponse")
}

func init() {
	proto.RegisterFile("pb-auth-gen/authen.proto", fileDescriptor_8d3b59a56bd496d6)
}

var fileDescriptor_8d3b59a56bd496d6 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x3d, 0x4f, 0xf3, 0x30,
	0x10, 0xc7, 0x9f, 0xf4, 0x69, 0x4b, 0x39, 0x81, 0x5a, 0x8e, 0x0a, 0xa2, 0x20, 0x21, 0xe4, 0x89,
	0xa5, 0xae, 0x04, 0x03, 0x2b, 0x2f, 0x12, 0x53, 0x07, 0x14, 0x36, 0xb6, 0xa4, 0x3d, 0x25, 0x51,
	0x15, 0xdb, 0xc4, 0x8e, 0xf8, 0x74, 0x7c, 0x37, 0x94, 0x17, 0x87, 0x24, 0x64, 0x41, 0x6c, 0xbe,
	0x17, 0xff, 0xef, 0xe7, 0xff, 0x19, 0x5c, 0x15, 0xae, 0x82, 0xdc, 0xc4, 0xab, 0x88, 0xc4, 0xba,
	0x38, 0x90, 0xe0, 0x2a, 0x93, 0x46, 0xe2, 0x48, 0x85, 0xec, 0x19, 0x8e, 0x36, 0x32, 0x4a, 0x84,
	0x4f, 0xef, 0x39, 0x69, 0x83, 0x1e, 0xcc, 0x72, 0x4d, 0x99, 0x08, 0x52, 0x72, 0x9d, 0x2b, 0xe7,
	0xfa, 0xd0, 0x6f, 0xe2, 0xa2, 0xa6, 0x02, 0xad, 0x3f, 0x64, 0xb6, 0x73, 0x47, 0x55, 0xcd, 0xc6,
	0xec, 0x15, 0x8e, 0x6b, 0x1d, 0xad, 0xa4, 0xd0, 0x84, 0x4b, 0x98, 0x18, 0xb9, 0x27, 0x51, 0xab,
	0x54, 0x01, 0x22, 0x8c, 0xb7, 0x72, 0x47, 0xe5, 0xf5, 0x89, 0x5f, 0x9e, 0xd1, 0x85, 0x83, 0x94,
	0xb4, 0x0e, 0x22, 0x72, 0xff, 0x97, 0xbd, 0x36, 0x64, 0x09, 0xcc, 0x7d, 0x8a, 0x12, 0x6d, 0x28,
	0xfb, 0x23, 0x1f, 0x5e, 0x02, 0x28, 0xca, 0xd2, 0x44, 0xeb, 0x44, 0x8a, 0x7a, 0x4e, 0x2b, 0xc3,
	0xee, 0x61, 0xf1, 0x3d, 0xaa, 0x7e, 0x82, 0x85, 0x75, 0x86, 0x61, 0x47, 0x5d, 0x58, 0x0e, 0x67,
	0x4f, 0x31, 0x6d, 0xf7, 0x2f, 0x8d, 0xa8, 0x65, 0x1e, 0xb4, 0x82, 0x45, 0x70, 0xfe, 0xa3, 0xbf,
	0x1e, 0xdc, 0x85, 0x75, 0xfa, 0xb0, 0xbf, 0x73, 0xf1, 0xe6, 0xd3, 0x81, 0xf1, 0x43, 0x6e, 0x62,
	0xe4, 0x30, 0x29, 0x77, 0x84, 0x0b, 0xae, 0x42, 0xde, 0x5e, 0xbb, 0x77, 0xd2, 0xca, 0x54, 0x10,
	0xec, 0x1f, 0xde, 0xc1, 0xcc, 0x7a, 0x82, 0xa7, 0x45, 0x43, 0x6f, 0x19, 0xde, 0xb2, 0x9b, 0x6c,
	0x2e, 0x6e, 0x60, 0xde, 0x7b, 0x1a, 0x7a, 0x45, 0xeb, 0xb0, 0x3f, 0xde, 0xc5, 0x60, 0xcd, 0xaa,
	0x3d, 0x4e, 0xdf, 0xc6, 0x7c, 0xad, 0xc2, 0x70, 0x5a, 0xfe, 0xda, 0xdb, 0xaf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xd5, 0x55, 0x4b, 0xf8, 0xd1, 0x02, 0x00, 0x00,
}
